---
- name: Install git
  apt:
    name:
      - git
      - python3-pip
      - python3
    state: present

- name: Install pip3
  pip:
    name:
      - python-dotenv

- name: Clone preprocessor
  git:
    repo: https://github:{{ github_token }}@github.com/starlinglab/integrity-preprocessor.git
    dest: /root/integrity-preprocessor
    force: yes
    version: dev


- name: Create starling config folder
  file:
    path: /root/.integrity/
    state: directory
    owner: root
    group: root
    mode: 0770

- name: Copy Config
  template:
    src: "recorder_data.json.j2"
    dest: /root/.integrity/preprocessor-id-config.json


- name: Copy .env
  template:
    src: "env.recorder-id.j2"
    dest: /root/integrity-preprocessor/integrity_recorder_id/.env

- name: Generate Config
  shell: "python3 /root/integrity-preprocessor/integrity_recorder_id/update_recorder_id.py"
  

- name: Install chatbot service
  copy:
    src: integrity-preprocessor-chatbot.service
    dest: /etc/systemd/system/integrity-preprocessor-chatbot.service
  when: integrity_preprocessor_chatbot == True

- name: Install browsertrix service
  copy:
    src: integrity-preprocessor-browsertrix.service
    dest: /etc/systemd/system/integrity-preprocessor-browsertrix.service
  when: integrity_preprocessor_browsertrix == True

- name: Install folder service
  copy:
    src: integrity-preprocessor-folder.service
    dest: /etc/systemd/system/integrity-preprocessor-folder.service
  when: integrity_preprocessor_folder == True

- name: Install browsertrix config
  template:
    src: env.browsertrix.j2
    dest: /root/integrity-preprocessor/browsertrix/.env
  when: integrity_preprocessor_browsertrix == True

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Start chatbot preprocessor
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: integrity-preprocessor-chatbot
  when: integrity_preprocessor_chatbot == true

- name: Start browsertrix preprocessor
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: integrity-preprocessor-browsertrix
  when: integrity_preprocessor_browsertrix == true

- name: Create starling config folder
  file:
    path: /root/.integrity/
    state: directory
    owner: root
    group: root
    mode: 0770

- name: Copy Config
  template:
    src: "recorder_data.json.j2"
    dest: /root/.integrity/preprocessor-id-config.json


- name: Copy .env
  template:
    src: "env.recorder-id.j2"
    dest: /root/integrity-preprocessor/integrity_recorder_id/.env

- name: Generate Config
  shell: "python3 /root/integrity-preprocessor/integrity_recorder_id/update_recorder_id.py"