---
- name: Install git
  apt:
    name:
      - git
      - python3-pip
      - python3
      - gnupg
    state: present

- name: Install pip3
  pip:
    name:
      - python-dotenv
      - watchdog
      - python-magic

- name: Clone preprocessor
  git:
    repo: https://github:{{ github_token }}@github.com/starlinglab/integrity-preprocessor.git
    dest: /root/integrity-preprocessor
    force: yes
    version: dev

- name: Create starling config folder
  file:
    path: /root/.integrity/
    state: directory
    owner: root
    group: root
    mode: 0770

# PreProcessor
- name: Create Pre-Processor ID Config
  template:
    src: "preprocessor-id-config.json.j2"
    dest: /root/.integrity/preprocessor-id-config.json

- name: Copy .env
  template:
    src: "env.recorder-id.j2"
    dest: /root/integrity-preprocessor/integrity_recorder_id/.env

- name: Generate Initial PreProcesor config
  shell: "python3 /root/integrity-preprocessor/integrity_recorder_id/update_recorder_id.py"

# PreProcessor Chat Bot
- name: Install chatbot service
  copy:
    src: integrity-preprocessor-chatbot.service
    dest: /etc/systemd/system/integrity-preprocessor-chatbot.service
  when: integrity_preprocessor_chatbot == True

- name: Copy .env
  copy:
    src: "integrity-preprocessor-chatbot.env"
    dest: /root/integrity-preprocessor/chat-bot/.env
  when: integrity_preprocessor_chatbot == True

- name: Copy config
  copy:
    src: "{{ integrity_preprocessor_chatbot_config }}"
    dest: /root/.integrity/preprocessor-chatbot.json
    force: no
  when: integrity_preprocessor_chatbot_config is defined
- name: Copy user database
  copy:
    src: "{{ integrity_preprocessor_chatbot_signal_user_config }}"
    dest: /root/.integrity/preprocessor-chatbot-signal-users.json
    force: no
  when: integrity_preprocessor_chatbot_signal_user_config is defined

- name: Copy config
  copy:
    src: "preprocessor-empty.json"
    dest: /root/.integrity/preprocessor-chatbot.json
    force: no
  when: integrity_preprocessor_chatbot == True

# PreProcessor Browsertrix
- name: Install browsertrix service
  copy:
    src: integrity-preprocessor-browsertrix.service
    dest: /etc/systemd/system/integrity-preprocessor-browsertrix.service
  when: integrity_preprocessor_browsertrix == True

- name: Install browsertrix config
  template:
    src: env.browsertrix.j2
    dest: /root/integrity-preprocessor/browsertrix/.env
  when: integrity_preprocessor_browsertrix == True

- name: Copy config
  copy:
    src: "{{ integrity_preprocessor_browsertrix_config }}"
    dest: /root/.integrity/preprocessor-browsertrix.json
    force: no
  when: integrity_preprocessor_browsertrix_config is defined

- name: Copy config (placeholder)
  copy:
    src: "preprocessor-empty.json"
    dest: /root/.integrity/preprocessor-browsertrix.json
    force: no
  when: integrity_preprocessor_browsertrix == True

  #PreProcessor Folder
- name: Install folder service
  copy:
    src: integrity-preprocessor-folder.service
    dest: /etc/systemd/system/integrity-preprocessor-folder.service
  when: integrity_preprocessor_folder == True

- name: Copy folder .env
  copy:
    src: "integrity-preprocessor-folder.env"
    dest: /root/integrity-preprocessor/folder/.env
  when: integrity_preprocessor_folder == True

- name: Copy folder .env
  copy:
    src: "{{ integrity_preprocessor_folder_config }}"
    dest: /root/.integrity/preprocessor-folder.json
    force: no
  when: integrity_preprocessor_folder_config is defined

- name: Copy folder .env (placeholder)
  copy:
    src: "preprocessor-empty.json"
    dest: /root/.integrity/preprocessor-folder.json
    force: no
  when: integrity_preprocessor_folder == True

# General
- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

# Start PreProcessor Services
- name: Start chatbot preprocessor
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: integrity-preprocessor-chatbot
  when: integrity_preprocessor_chatbot == true

- name: Start browsertrix preprocessor
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: integrity-preprocessor-browsertrix
  when: integrity_preprocessor_browsertrix == true
