---
- hosts: "ipfs"
  become: true
  roles:
    - reboot
    - sshkey_update
    - hypha.common.provision_ssh_keys
    - hypha.common.common
    - hypha.common.firewall
    - hypha.common.harden_ssh
    - hypha.common.node_exporter
    - prometheus_addnode
    - ipfs
    - ipfs_cluster
