---
- name: Install git
  apt:
    name:
      - git

- name: telegram-archive-bot
  git:
    repo: https://github:{{ github_token }}@github.com/numbersprotocol/telegram-archive-bot.git
    dest: /root/telegram_archive_bot_{{ telegram_bot.key }}
    force: yes

- name: Create store directory
  file:
    path: /mnt/store
    state: directory

- name: Create telegram bot directory
  file:
    path: /mnt/store/telegram_archive_bot_{{ telegram_bot.key }}
    state: directory

- name: Configure archive
  template:
    src: config.json.j2
    dest: '/root/telegram_archive_bot_{{ telegram_bot.key }}/telegram_archive_bot/config.json'

### Enable LOKI Logger Driver and settings
- name: Install LOKI Driver
  shell: "docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions"
  when: browsertrix_loki is defined
  ignore_errors: true

- name: Enable Docker-Compose Overrides for Logging
  ansible.builtin.template:
    src: docker-compose.override.yml.j2
    dest: /root/telegram_archive_bot_{{ telegram_bot.key }}/telegram_archive_bot/docker-compose.override.yaml

- name: Map Data Dir
  lineinfile:
    path: /root/telegram_archive_bot_{{ telegram_bot.key }}/telegram_archive_bot/docker-compose.yml
    regex: "      - /mnt/store/telegram_archive_bot_{{ telegram_bot.key }}/data:/data"
    insertafter: "    volumes:"
    line: "      - /mnt/store/telegram_archive_bot_{{ telegram_bot.key }}/data:/data"

- name: Map Archive Dir
  lineinfile:
    path: /root/telegram_archive_bot_{{ telegram_bot.key }}/telegram_archive_bot/docker-compose.yml
    regex: "      - /mnt/store/telegram_archive_bot_{{ telegram_bot.key }}/archive:/archive"
    insertafter: "    volumes:"
    line: "      - /mnt/store/telegram_archive_bot_{{ telegram_bot.key }}/archive:/archive"

- name: Set restart on
  lineinfile:
    path: /root/telegram_archive_bot_{{ telegram_bot.key }}/telegram_archive_bot/docker-compose.yml
    regex: "    restart:"
    insertafter: "  archive:"
    line: "    restart: unless-stopped"

- name: docker-compose build
  command: docker-compose build
  args:
      chdir: /root/telegram_archive_bot_{{ telegram_bot.key }}/telegram_archive_bot

- name: docker-compose up -d
  command: docker-compose up -d
  args:
      chdir: /root/telegram_archive_bot_{{ telegram_bot.key }}/telegram_archive_bot