---
- name: Create Aleph directory
  file:
    path: /root/aleph
    state: directory

- name: Create data directory
  file:
    path: /mnt/sdb1
    state: directory


- name: Create data directory
  file:
    path: /mnt/sdb1/aleph_data
    state: directory

- name: Download latest docker-compose.yml
  get_url:
    url: https://raw.githubusercontent.com/alephdata/aleph/main/docker-compose.yml
    dest: /root/aleph/docker-compose.yml

- name: Update archive path for aleph
  replace:
    path: /root/aleph/docker-compose.yml
    regexp: "      - archive-data:/data"
    replace:  "      - /mnt/sdb1/aleph_data:/data"

- name: Template config for Aleph
  ansible.builtin.template:
    src: aleph.env.j2
    dest: /root/aleph/aleph.env

- name: Setting sysctl values
  sysctl: name=vm.max_map_count value=262144 sysctl_set=yes
  with_items:
    - { name: "vm.max_map_count", value: 262144}

- name: docker-compose up
  command: docker-compose up -d
  args:
      chdir: /root/aleph

- name: prepeare database
  command: docker-compose run --rm shell aleph upgrade
  args:
      chdir: /root/aleph

- name: Add User
  command: docker-compose run --rm shell aleph createuser --name="Starling" --admin --password={{aleph_admin_password}}  {{ aleph_admin_email }}
  args:
      chdir: /root/aleph
