---
- name: Install git
  apt:
    name:
      - git
      - python3
      - python3-pip      

- name: Install pipenv python package
  pip:
    name:
      - pipenv
      - opentimestamps-client

- name: Create starling group
  group:
    name: starling    

- name: Create starling user
  user:
    name: starling
    state: present
    comment: starling User
    createhome: yes
    groups: starling
    shell: /bin/bash

- name: Create starling config folder
  file:
    path: /home/starling/.integrity/
    state: directory
    owner: starling
    group: starling
    mode: 0770

- name: Creates directory
  file:
    path: "{{ integrity_data_path }}"
    state: directory
    owner: starling
    group: starling
    mode: 0775
    recurse: yes

- name: Download ISCN code
  git:
    repo: https://github.com/likecoin/iscn-js.git
    dest: /home/starling/iscn
    version: feature/server_example
    force: yes

- name: Init env
  ansible.builtin.shell: npm install
  args:
    chdir: /home/starling/iscn/sample/server


- name: Configure ISCN service
  template:
    src: iscn.service.j2
    dest: /etc/systemd/system/iscn.service

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
   
- name: Start ISCN service
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: iscn


- name: Download sintegrity-backend server
  git:
    repo: https://github:{{ github_token }}@github.com/starlinglab/integrity-backend.git
    dest: /home/starling/integrity-backend
    force: yes
    version: dev-with-c2pa-proofmode

- name: Init env
  ansible.builtin.shell: /usr/bin/su - starling -c 'cd /home/starling/integrity-backend/ && pipenv install'
  args:
    chdir: /home/starling/integrity-backend/

- name: env config file
  template: 
    src: env.j2
    dest: '/home/starling/integrity-backend/.env'


- name: Copy claim tool
  copy:
    src: claim_tool
    dest: /home/starling/claim_tool
    group: starling
    owner: starling    
    mode: 0550

- name: Create claim tool folder
  file:
    path: /home/starling/.cai/
    state: directory
    owner: starling
    group: starling
    mode: 0550

- name: Configure Claim tool 1/1
  copy:
    src: "{{ integrity_cai_signing_key_file }}.pem"
    dest: /home/starling/.cai/temp_key.pem
    group: starling
    owner: starling
    mode: 0550
  when: integrity_cai_signing_key_file is defined

- name: Configure Claim tool 2/2
  copy:
    src: "{{ integrity_cai_signing_key_file }}.pub"
    dest: /home/starling/.cai/temp_key.pub
    group: starling
    owner: starling
    mode: 0550
  when: integrity_cai_signing_key_file is defined

- name: Copy config file
  copy:
    src: "{{integrity_backend_config}}"
    dest: /home/starling/.integrity/backend-config.json
    owner: starling
    group: starling
    mode: 0666
    force: no
  when: integrity_backend_config is defined


- name: Copy config file
  copy:
    src: /home/starling/integrity-backend/config.example.json
    dest: /home/starling/.integrity/backend-config.json
    remote_src: yes
    owner: starling
    group: starling
    mode: 0666
    force: no    

- name: Configure service
  copy:
    src: integrity-backend.service
    dest: /etc/systemd/system/integrity-backend.service

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
   
- name: Start integrity backend service
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: integrity-backend

