---
- name: Install git
  apt:
    name:
      - git

- name: Clone Broswerix
  git:
    repo: https://github.com/webrecorder/browsertrix-cloud.git
    dest: /root/browsertrix
    force: yes
    
- name: Template config for browsertrix
  ansible.builtin.template:
    src: config.env.j2
    dest: /root/browsertrix/configs/config.env
    owner: root
    group: root
    mode: '0644'

- name: Template config for browserix
  ansible.builtin.template:
    src: signing.yaml.j2
    dest: /root/browsertrix/configs/signing.yaml
    owner: root
    group: root
    mode: '0644'
    
- name: Move browsetrix from port 80
  lineinfile:
    path: /root/browsertrix/docker-compose.yml
    regex: 80:80
    line: "      - 81:80"

- name: Move browsetrix from port 80
  lineinfile:
    path: /root/browsertrix/docker-compose.yml
    line: "      - 127.0.0.1:8080:8080"
    regex: "127.0.0.1:8080:8080"
    insertafter: "      - 81:80"
 

- name: Create browsertrix data folder
  file:
    path: /mnt/browsertrix
    state: directory

- name: Move browsertrix storage to different folder
  lineinfile:
    path: /root/browsertrix/docker-compose.yml
    regex: btrix-minio-data:/data
    line: "      - /mnt/browsertrix:/data"      

### Enable LOKI Logger Driver and settings
- name: Install LOKI Driver
  shell: "docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions"
  when: browsertrix_loki is defined
  ignore_errors: true

- name: Enable Docker-Compose Overrides for Logging
  ansible.builtin.template:
    src: docker-compose.override.yml.j2
    dest: /root/browsertrix/docker-compose.override.yml

### Prepeare browstrix contrib folder ##
- name: Create browsertrix contrib folder
  file:
    path: /root/browsertrix-contrib
    state: directory

- name: Copy over profile
  copy:
    src: "{{browsertrix_profile_file}}"
    dest: /root/browsertrix-contrib/profile.tar.gz
    group: root
    owner: root
    mode: 0555
  when: browsertrix_profile_file is defined

- name: Template uploadFile for browsertrix for profile
  ansible.builtin.template:
    src: uploadFile.sh
    dest: /root/browsertrix-contrib/uploadFile.sh
    group: root
    owner: root
    mode: 0755

- name: Template createAccount for browsertrix
  copy:
    src: createAccount.py
    dest: /root/browsertrix-contrib/createAccount.py
    group: root
    owner: root
    mode: 0755

- name: docker-compose build
  command: docker-compose up -d
  args:
    chdir: /root/browsertrix

- name: docker-compose pull crawler
  command: docker pull webrecorder/browsertrix-crawler:latest
  args:
    chdir: /root/browsertrix


- name: Upload profile
  command: ./uploadFile.sh test-bucket profile.tar.gz
  args:
    chdir: /root/browsertrix-contrib

- name: Create master account
  command: "./createAccount.py {{ browsertrix_user_email }} {{ browsertrix_user_password }} MasterArchive"
  args:
    chdir: /root/browsertrix-contrib
  register: account_creation

- name: Set AID Value
  set_fact:
    browsertrix_integrity_aid = {{ account_creation.stdout }}
  when: 
    - account_creation is defined
    - account_creation != ""
